[project]
name = "kursachbackend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "selenium>=4.39.0",
    "webdriver-manager>=4.0.2",
    "redis>=7.1.0",
    "feedparser>=6.0.12",
    "litestar>=2.18.0",
    "granian>=2.6.0",
]
